### ISSUE TITLE
Update USB 3G Modem link?

### ISSUE THREAD

**Issue by pinzler** [twilio/wireless-security-camera#1]
The link to the USB 3G Modem on the readme page goes to a "Sorry, We can't find this Item. Please check your Item#" page on newegg.

**Comment by jonedavis** [comment]
Hey @pinzler, apologies for the inconvenience, and thanks for pointing this out. The [LTE](https://www.amazon.com/Unlocked-Huawei-E397u-53-Worldwide-Required/dp/B01M0JY15V/ref=sr_1_1?ie=UTF8&qid=1496276301&sr=8-1&keywords=3g+lte+usb+modem) option is a better choice. We're in the process of updating this blueprint now so going with the LTE will work better in the long run. The only downside is that this specific LTE module will not fit in the 3d printout. I'll search for a USB module that fits in the printout, and update the link asap.

Thanks,
Jon
